###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

megogo-memcached:
  image: phpdockerio/memcached:latest
  container_name: megogo-memcached

megogo-redis:
  image: phpdockerio/redis:latest
  container_name: megogo-redis

megogo-mysql:
  image: mysql:5.7
  container_name: megogo-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=test
    - MYSQL_DATABASE=test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test
  ports:
    - "3336:3306"

megogo-webserver:
  image: phpdockerio/nginx:latest
  container_name: megogo-webserver
  volumes:
      - ../www:/var/www/megogo
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8080:80"
  links:
   - megogo-php-fpm

megogo-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: megogo-php-fpm
  volumes:
    - ../www:/var/www/megogo
    - ./php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
  links:
    - megogo-memcached
    - megogo-mysql
    - megogo-redis
